from collections.abc import Callable

import torch
import torch.nn as nn
from relax_xai.relax import RELAX

from repeat_xai.thresholds import get_threshold_method


class REPEAT(nn.Module):
    """
    Class for REPEAT, a framework for uncertainty estimation in
    representation learning explainability.

    Link to ArXiv paper: https://arxiv.org/abs/2412.08513
    Link to AAAI version: https://doi.org/10.1609/aaai.v39i8.32900

    REPEAT treats each pixel in an image as a Bernoulli random variable that
    is either important or unimportant for the representation of the image.
    Bernoulli samples are generated by repeatedly running a stochastic
    representation learning explainability (R-XAI) method (RELAX by default),
    and thresholding each importance map into important and unimportant
    pixels. From the weighted Bernoulli samples, the probability of each
    pixel being important is estimated, along with the associated
    uncertainty, thus enabling users to ascertain certainty in pixel
    importance.

    All encoder evaluations are wrapped in torch.no_grad(), so no gradients
    are tracked.

    Parameters
    ----------
    input_image
        Input image to be explained, with shape (1, C, H, W).
    encoder
        Encoder that transforms the input image into a new representation.
        Must accept batched inputs with shape (N, C, H, W).
    num_repeats
        How many times to repeat the base R-XAI computation (K in the paper).
        Each repeat gives one Bernoulli sample per pixel.
    batch_size
        The size of each batch of masks in each base R-XAI run.
    num_batches
        Number of batches with masks to generate in each base R-XAI run.
    similarity_measure
        Function for measuring similarity between masked and unmasked
        representations, passed on to each RELAX run. Called as
        similarity_measure(unmasked, masked), where both tensors have shape
        (batch_size, D), and should return a tensor of similarity scores with
        shape (batch_size,). Defaults to cosine similarity.
    explanation_threshold
        Method used to threshold each importance map into important and
        unimportant pixels: one of 'mean', 'otsu', 'triangle' or 'li', or a
        callable that takes a tensor of importance scores and returns a
        threshold value. Defaults to 'mean', which was found to work best in
        the paper.
    """

    def __init__(
        self,
        input_image: torch.Tensor,
        encoder: nn.Module,
        num_repeats: int = 10,
        batch_size: int = 100,
        num_batches: int = 10,
        similarity_measure: nn.Module | None = None,
        explanation_threshold: str | Callable[[torch.Tensor], torch.Tensor] = "mean",
    ) -> None:
        super().__init__()

        if input_image.ndim != 4 or input_image.shape[0] != 1:
            raise ValueError(
                f"input_image must have shape (1, C, H, W), got {tuple(input_image.shape)}."
            )

        self.input_image = input_image
        self.num_repeats = num_repeats
        self.batch_size = batch_size
        self.num_batches = num_batches
        self.device = input_image.device
        self.shape = tuple(input_image.shape[2:])
        self.encoder = encoder.to(self.device)
        self.encoder.eval()
        self.similarity_measure = similarity_measure
        self.explanation_threshold = explanation_threshold
        self.threshold_method = get_threshold_method(explanation_threshold)

        self.probability_of_importance = torch.zeros(self.shape, device=self.device)
        self.uncertainty = torch.zeros(self.shape, device=self.device)

    def forward(self, **kwargs) -> None:
        """
        Runs REPEAT. Keyword arguments are passed on to each RELAX run, and
        from there to mask_generator (e.g. num_cells and
        probability_of_drop).
        """

        self.probability_of_importance = torch.zeros(self.shape, device=self.device)
        self.uncertainty = torch.zeros(self.shape, device=self.device)

        with torch.no_grad():
            for _ in range(self.num_repeats):
                relax = RELAX(
                    self.input_image,
                    self.encoder,
                    batch_size=self.batch_size,
                    num_batches=self.num_batches,
                    similarity_measure=self.similarity_measure,
                )
                relax.forward(**kwargs)

                importance = relax.importance

                threshold_value = self.threshold_method(importance)

                # Bernoulli sample, weighted by the (max-normalized) base
                # importance scores (Eq. 3 and 5 in the paper).
                weight = importance / importance.max()
                self.probability_of_importance += weight * (importance >= threshold_value)

        # Weighted sample mean over the repeats (Eq. 4 in the paper).
        self.probability_of_importance /= self.num_repeats

        # Uncertainty as the variance of a Bernoulli random variable
        # (Eq. 6 in the paper). High for pixels that fluctuate between
        # important and unimportant, low for pixels that are consistently
        # one or the other.
        self.uncertainty = self.probability_of_importance * (1 - self.probability_of_importance)

        return None
